# Generated by Django 3.1.14 on 2022-01-12 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0002_auto_20220111_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='previous_evolution',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=models.SET('Неизвестно'), related_name='previous_evolutions', to='pokemon_entities.pokemon'),
        ),
    ]
